# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcat_cpp <- function(support, prob, num_samples) {
    .Call('_agents_rcat_cpp', PACKAGE = 'agents', support, prob, num_samples)
}

rcat_vectorized_cpp <- function(support, prob) {
    .Call('_agents_rcat_vectorized_cpp', PACKAGE = 'agents', support, prob)
}

compute_qvalues_condber <- function(I, alpha) {
    .Call('_agents_compute_qvalues_condber', PACKAGE = 'agents', I, alpha)
}

rcondber_cpp <- function(I, alpha) {
    .Call('_agents_rcondber_cpp', PACKAGE = 'agents', I, alpha)
}

rcondber_vectorized_cpp <- function(I, alpha) {
    .Call('_agents_rcondber_vectorized_cpp', PACKAGE = 'agents', I, alpha)
}

rcondber_mcmc_cpp <- function(I, alpha, mcmc_iterations) {
    .Call('_agents_rcondber_mcmc_cpp', PACKAGE = 'agents', I, alpha, mcmc_iterations)
}

rcondber_mcmc_vectorized_cpp <- function(I, alpha, mcmc_iterations) {
    .Call('_agents_rcondber_mcmc_vectorized_cpp', PACKAGE = 'agents', I, alpha, mcmc_iterations)
}

compute_qvalues_dpoibin <- function(alpha) {
    .Call('_agents_compute_qvalues_dpoibin', PACKAGE = 'agents', alpha)
}

dpoibin_cpp <- function(eval, alpha) {
    .Call('_agents_dpoibin_cpp', PACKAGE = 'agents', eval, alpha)
}

dpoibin_vectorized_cpp <- function(eval, alpha) {
    .Call('_agents_dpoibin_vectorized_cpp', PACKAGE = 'agents', eval, alpha)
}

multinomial_resampling_cpp <- function(weights, ndraws) {
    .Call('_agents_multinomial_resampling_cpp', PACKAGE = 'agents', weights, ndraws)
}

systematic_resampling_cpp <- function(weights, ndraws) {
    .Call('_agents_systematic_resampling_cpp', PACKAGE = 'agents', weights, ndraws)
}

sis_alpha_full <- function(X, I, lambda, gamma) {
    .Call('_agents_sis_alpha_full', PACKAGE = 'agents', X, I, lambda, gamma)
}

sis_alpha_net <- function(X, lambda, gamma, adjacency, degree) {
    .Call('_agents_sis_alpha_net', PACKAGE = 'agents', X, lambda, gamma, adjacency, degree)
}

sis_compute_infected_prob <- function(log_poibin, log_policy) {
    .Call('_agents_sis_compute_infected_prob', PACKAGE = 'agents', log_poibin, log_policy)
}

sis_approximate_infected_prob <- function(log_sumbin, log_policy) {
    .Call('_agents_sis_approximate_infected_prob', PACKAGE = 'agents', log_sumbin, log_policy)
}

dsumbin_cpp <- function(eval, n1, p1, n2, p2) {
    .Call('_agents_dsumbin_cpp', PACKAGE = 'agents', eval, n1, p1, n2, p2)
}

dsumbin_vectorized_cpp <- function(eval, n1, p1, n2, p2) {
    .Call('_agents_dsumbin_vectorized_cpp', PACKAGE = 'agents', eval, n1, p1, n2, p2)
}

dtranspoi_poibin_approx_cpp <- function(eval, alpha) {
    .Call('_agents_dtranspoi_poibin_approx_cpp', PACKAGE = 'agents', eval, alpha)
}

dtranspoi_poibin_approx_vectorized_cpp <- function(eval, alpha) {
    .Call('_agents_dtranspoi_poibin_approx_vectorized_cpp', PACKAGE = 'agents', eval, alpha)
}

dtranspoi_cpp <- function(eval, mu, sigmasq, end_support) {
    .Call('_agents_dtranspoi_cpp', PACKAGE = 'agents', eval, mu, sigmasq, end_support)
}

dtranspoi_vectorized_cpp <- function(eval, mu, sigmasq, end_support) {
    .Call('_agents_dtranspoi_vectorized_cpp', PACKAGE = 'agents', eval, mu, sigmasq, end_support)
}

